### ISSUE TITLE
Data path doesn't work with jar file

### ISSUE THREAD

**Issue by mistaluai** [mistaluai/EmployeeAttendanceSystem#45]
the data path you provided in your file handler only works in the IntelliJ, when I build the jar file it doesn't detect the path.
please fix asap...

**Comment by BlindFl0W** [comment]
I will look into that.

**Comment by mistaluai** [comment]
> I will look into that.

Can't we just ask the user to provide the directory/file that contains the employee data? And for the attendance history files we handle their path without asking the user to do so.

I guess this will make it a whole lot better and easier, I can't implement this in the front end easily.

**Comment by BlindFl0W** [comment]
We can.
But I feel like all the company data should be in a static place as It is a data base not just an input file.
I Think It should work fine in its current state. We will look into it today.

**Comment by mistaluai** [comment]
> We can.
> But I feel like all the company data should be in a static place as It is a data base not just an input file.
> I Think It should work fine in its current state. We will look into it today.

You should keep in mind that you will need to handle the data paths across multiple platforms.

**Comment by mistaluai** [comment]
I have a solution in mind.
the jar file directory will be our main directory, the csv files will be in the same directory with our app, so we can access/modify it easily without the need of the user deciding where the files should be, this solution will be cross-platform also.
the steps should be like this
1- [Check if you're running through jar file or not](https://stackoverflow.com/questions/482560/can-you-tell-on-runtime-if-youre-running-java-from-within-a-jar#:~:text=If%20you%27re%20running%20from,directory%20containing%20your%20class%20files.)
2- [Get the path of the current jar file](https://www.w3docs.com/snippets/java/how-to-get-the-path-of-a-running-jar-file.html#:~:text=To%20get%20the%20path%20of%20a%20running%20JAR%20file%2C%20you,and%20then%20the%20getCodeSource%20method.&text=This%20will%20return%20the%20path,file%20containing%20the%20MyClass%20class.)
3- now we know the path of our executable and the files we are looking for should be around it.

**Comment by ZiadMohamed9** [comment]
fuck u

**Comment by BlindFl0W** [comment]
The file handling should fine across multiple platforms. I feel like we don't have to over engineer it.
We will test it today and decide.

**Comment by mistaluai** [comment]
issue was fixed by added the data files to the jar directory since we were using a relative path.
