### ISSUE TITLE
error in marking attendance

### ISSUE THREAD

**Issue by mistaluai** [mistaluai/EmployeeAttendanceSystem#48]
whenever I try to mark attendance it gives the following error

<img width="830" alt="image" src="https://github.com/mistaluai/EmployeeAttendanceSystem/assets/20214546/5212cb47-630f-4ef5-96bc-0822c0f17fbf">

NullPointerException
at Backend.AttendanceManagment.AttendanceManager.markAttendance(AttendanceManager.java:43)
	at Backend.AttendanceManagment.AttendanceCommands.MarkAttendance.execute(MarkAttendance.java:12)
	at Backend.Entities.Employee.markAttendance(Employee.java:82)

**Comment by mistaluai** [comment]
more details:

`if (attendanceRecords.size() != 0){
            if (attendanceRecords.get(attendanceRecords.size() - 1).getTimeOut() == null){
                attendanceState = new InState();
            }
        }else{
            attendanceState = new OutState();
        }`

as you can see this checks on the last attendance record, and if the time out is null it will initialise the employee's state as in state, but what about if it wasn't null ? this case wasn't handled, the attendance state will be null, the solution to this is to init an out state and create a new attendance record for the employee (this is quite complex as you need to check if it has been a new day or not, otherwise it will cause conflicts)

**Comment by ZiadMohamed9** [comment]
I think issue is solved, try to test.
