### ISSUE TITLE
Attendance Command Implementation

### ISSUE THREAD

**Issue by BlindFl0W** [mistaluai/EmployeeAttendanceSystem#8]
Some attendance command implementation needs reconsideration. also needs more docs.

**Comment by mistaluai** [comment]
provide more details.

**Comment by BlindFl0W** [comment]
We will need to change some methods's parameters and fix some implementation errors.
I got it.

**Comment by BlindFl0W** [comment]
Don't close this. It will be closed with a pr when it's completed.
